# Generated by Django 4.0.6 on 2022-07-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=11)),
                ('addmission_year', models.DateField(blank=True)),
                ('stream', models.CharField(blank=True, max_length=10)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('enrolment_number', models.CharField(blank=True, max_length=12)),
                ('student_name', models.CharField(blank=True, default='Student Name', max_length=80)),
                ('admission_type', models.CharField(blank=True, max_length=100)),
                ('tuition_fee', models.IntegerField(blank=True, default=0)),
                ('received_sum', models.IntegerField(blank=True, default=0)),
                ('penalty', models.IntegerField(blank=True, default=0)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('payment_mode', models.CharField(blank=True, max_length=10)),
                ('transaction_number', models.BigIntegerField(blank=True, default=0)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('bank_number', models.IntegerField(blank=True, default=0)),
                ('document_number', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
    ]
