# Generated by Django 4.0.6 on 2022-07-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeformat',
            name='addmission_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='admission_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='bank_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='cheque_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='document_number',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='enrolment_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='payment_mode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='penalty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='received_sum',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='semester',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='stream',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='student_name',
            field=models.CharField(default='Student Name', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='transaction_number',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='tuition_fee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
