# Generated by Django 4.0.6 on 2022-07-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0002_alter_feeformat_addmission_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeformat',
            old_name='addmission_year',
            new_name='AdYear',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='stream',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='enrolment_number',
            new_name='Enrollment',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='student_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='semester',
            new_name='Sem',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='type',
            new_name='Type',
        ),
    ]
