# Generated by Django 4.0.6 on 2022-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0003_rename_addmission_year_feeformat_adyear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeformat',
            old_name='penalty',
            new_name='Bank',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='document_number',
            new_name='ChNo',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='transaction_number',
            new_name='DocumentNo',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='payment_mode',
            new_name='MOP',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='received_sum',
            new_name='Penalty',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='total',
            new_name='ReceivedFees',
        ),
        migrations.RenameField(
            model_name='feeformat',
            old_name='tuition_fee',
            new_name='Total',
        ),
        migrations.RemoveField(
            model_name='feeformat',
            name='admission_type',
        ),
        migrations.RemoveField(
            model_name='feeformat',
            name='bank_number',
        ),
        migrations.RemoveField(
            model_name='feeformat',
            name='cheque_date',
        ),
        migrations.AddField(
            model_name='feeformat',
            name='AdmissionType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feeformat',
            name='Date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feeformat',
            name='TuitionFee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='AdYear',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feeformat',
            name='Type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
