# Generated by Django 4.0.6 on 2022-07-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeStructure', '0004_rename_penalty_feeformat_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeformat',
            name='ChNo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
